Run include guard check on concept exercises

diff --git a/bin/check-include-guards b/bin/check-include-guards
--- a/bin/check-include-guards
+++ b/bin/check-include-guards
@@ -2,11 +2,17 @@
 
 set +e
 
+usage="check-include-guards - checks include guards for all exercises in a given directory
+Usage:
+  check-include-guards <path-to-exercises>
+
+Example:
+  check-include-guards ./exercises/concept ./exercises/practice"
+
 ERROR_COUNT=0
 
-echo "Checking include guards format"
-
 check_guard() {
+    # Check the include guards in a given file
     if [ -f "$1" ]; then
         if grep -LPzo "$2" "$1" > /dev/null; then
             printf "%s does not have correctly formatted include guards\n" "$1"
@@ -15,21 +21,43 @@ check_guard() {
     fi
 }
 
-for directory in ./exercises/practice/*; do
-    slug=$(basename "${directory}")
-    stub=$(printf "%s" "${slug}" | tr "-" "_")
-    macro=$(printf "%s" "${stub}_H" | tr "[:lower:]" "[:upper:]");
-    guard="#ifndef ${macro}\n#define ${macro}"
+check_exercises () {
+    # Check all exercises in a given directory
+    for directory in "${1}"/*; do
+        slug=$(basename "${directory}")
+        stub=$(printf "%s" "${slug}" | tr "-" "_")
+        macro=$(printf "%s" "${stub}_H" | tr "[:lower:]" "[:upper:]");
+        guard="#ifndef ${macro}\n#define ${macro}"
 
-    practice="${directory}/${stub}.h"
-    check_guard "$practice" "$guard"
-    (( ERROR_COUNT+=$? ))
+        practice="${directory}/${stub}.h"
+        check_guard "$practice" "$guard"
+        (( ERROR_COUNT+=$? ))
 
-    example="${directory}/.meta/example.h"
-    check_guard "$example" "$guard"
-    (( ERROR_COUNT+=$? ))
-done
+        example="${directory}/.meta/example.h"
+        check_guard "$example" "$guard"
+        (( ERROR_COUNT+=$? ))
+    done
+}
 
-echo "Include guard check complete"
+if [ $# -gt 0 ]
+then
+    echo "Checking include guards format"
 
-exit "${ERROR_COUNT}"
+    for directory
+    do
+        if [ -d "${directory}" ]
+        then
+            check_exercises "${directory}"
+        else
+            echo "WARNING: Directory not found. Ignoring: ${1}"
+        fi
+    done
+
+    echo "Include guard check complete"
+
+    exit "${ERROR_COUNT}"
+else
+    echo "${usage}"
+    echo ""
+    exit 1
+fi
